import '../models/spot_data.dart';

final List<SpotData> kHiddenSpots = [
  // ========== 일출 명소 ==========
  SpotData(
    name: '간절곶',
    description: '한반도에서 가장 먼저 해가 뜨는 곳. 매년 해맞이 축제가 열립니다.',
    lat: 35.3622,
    lng: 129.3648,
    type: SpotType.sunrise,
    tags: ['해맞이', '등대', '울산'],
    shootingTip: '등대 왼쪽 해안 데크에서 수평선을 향해 촬영하면 해와 등대를 함께 담을 수 있습니다.',
    compositionTip: '전경에 갯바위를 넣고 삼분할 구도로 수평선을 하단 1/3에 배치하세요.',
    photoUrls: [
      'https://www.koreatravelpost.com/wp-content/uploads/2020/12/Ganjeolgot-sunrise.jpg',
      'https://www.koreatravelpost.com/wp-content/uploads/2020/12/Ganjeolgot-performance-1.jpg',
      'https://blog.trazy.com/wp-content/uploads/2019/10/ulsan-sunset-600x399.jpg',
    ],
  ),
  SpotData(
    name: '정동진',
    description: '서울에서 가장 가까운 동해안 일출 명소. 모래시계 공원이 유명합니다.',
    lat: 37.6898,
    lng: 129.0344,
    type: SpotType.sunrise,
    tags: ['기차역', '모래시계', '강릉'],
    shootingTip: '해변 모래사장에서 모래시계 공원과 일출을 함께 담거나, 기차역 플랫폼에서 바다를 배경으로 촬영하세요.',
    compositionTip: '모래시계를 중경에 두고 해를 우측 상단에 배치하면 균형잡힌 구도가 됩니다.',
    photoUrls: [
      'https://www.koreatravelpost.com/wp-content/uploads/2020/12/Jeongdongjin-sunrise.jpg',
      'https://blog.trazy.com/wp-content/uploads/2022/12/jeongdongjin_sunrise_blog-001.jpg',
      'https://tong.visitkorea.or.kr/cms/resource/12/2939812_image2_1.jpg',
    ],
  ),
  SpotData(
    name: '성산일출봉',
    description: '유네스코 세계자연유산. 제주도를 대표하는 일출 명소입니다.',
    lat: 33.4590,
    lng: 126.9425,
    type: SpotType.sunrise,
    tags: ['유네스코', '화산', '제주'],
    shootingTip: '일출봉 정상에서 촬영하거나, 아래 해변에서 화산체 전체를 담는 것을 추천합니다.',
    compositionTip: '광각렌즈로 일출봉의 웅장한 분화구와 떠오르는 해를 같이 구도에 넣으세요.',
    photoUrls: [
      'https://www.koreatravelpost.com/wp-content/uploads/2020/12/seongsan-sunrise.jpg',
      'https://triptins.com/wp-content/uploads/2023/03/Seongsan-Ilchulbong.jpeg',
      'https://triptins.com/wp-content/uploads/2023/03/Sunrise-Peak-Jeju-1024x768.jpeg',
    ],
  ),
  SpotData(
    name: '호미곶',
    description: '한반도 호랑이 꼬리 끝. 상생의 손 조형물이 있습니다.',
    lat: 36.0766,
    lng: 129.5680,
    type: SpotType.sunrise,
    tags: ['상생의손', '포항', '해맞이'],
    shootingTip: '상생의 손 조형물 뒤편에서 손과 해를 함께 프레임에 담으면 극적인 실루엣 샷을 얻을 수 있습니다.',
    compositionTip: '손 조형물을 좌측이나 우측에 배치하고 해를 반대편에 두어 시선 흐름을 만드세요.',
    photoUrls: [
      'https://blog.trazy.com/wp-content/uploads/2022/12/homigot_sunrise_blog-001.jpg',
      'https://www.koreatravelpost.com/wp-content/uploads/2020/12/Homigot-Sunrise-Festival.jpg',
      'https://www.koreatravelpost.com/wp-content/uploads/2020/12/Homigot-fireowrks.jpg',
    ],
  ),
  SpotData(
    name: '주문진 방파제',
    description: 'BTS 앨범 재킷 촬영지로 유명한 동해안 일출 포인트입니다.',
    lat: 37.8939,
    lng: 128.8207,
    type: SpotType.sunrise,
    tags: ['BTS', '방파제', '강릉'],
    shootingTip: '빨간 등대가 있는 방파제 끝에서 촬영하면 등대와 파도, 일출을 모두 담을 수 있습니다.',
    compositionTip: '긴 방파제 길을 리딩라인으로 활용해 시선을 수평선의 해로 유도하세요.',
    photoUrls: [
      'https://blog.trazy.com/wp-content/uploads/2022/12/jeongdongjin_sunrise_blog-001.jpg',
      'https://blog.trazy.com/wp-content/uploads/2019/10/naksan_sunrise_blog-001.jpg',
      'https://tong.visitkorea.or.kr/cms/resource/13/2939813_image2_1.jpg',
    ],
  ),
  SpotData(
    name: '월정리 해변',
    description: '에메랄드빛 바다와 하얀 모래가 어우러진 제주 동쪽 해변입니다.',
    lat: 33.5560,
    lng: 126.8556,
    type: SpotType.sunrise,
    tags: ['해변', '카페거리', '제주'],
    shootingTip: '해변의 하얀 모래사장 또는 카페거리의 야자수 사이에서 에메랄드빛 바다와 일출을 촬영하세요.',
    compositionTip: '전경에 검은 현무암이나 야자수를 배치하고 떠오르는 해를 배경으로 실루엣 효과를 주세요.',
    photoUrls: [
      'https://triptins.com/wp-content/uploads/2023/03/Udo-Island-View-1024x768.jpeg',
      'https://triptins.com/wp-content/uploads/2023/03/Jeju-Island-Sunrise-Peak-1024x768.jpeg',
      'https://www.koreatravelpost.com/wp-content/uploads/2020/12/seongsan-sunrise.jpg',
    ],
  ),
  SpotData(
    name: '대왕암 공원',
    description: '울산 동쪽 끝 바위 공원. 기암절벽 사이로 떠오르는 일출이 장관입니다.',
    lat: 35.4961,
    lng: 129.4362,
    type: SpotType.sunrise,
    tags: ['기암절벽', '울산', '산책로'],
    shootingTip: '산책로 전망대에서 대왕암 바위와 그 사이로 떠오르는 해를 프레임에 담으세요.',
    compositionTip: '기암절벽을 전경이나 중경에 배치하고 바위 틈새로 해를 넣어 프레임 구도를 만드세요.',
    photoUrls: [
      'https://blog.trazy.com/wp-content/uploads/2019/10/ulsan-sunset-600x399.jpg',
      'https://www.koreatravelpost.com/wp-content/uploads/2020/12/Ganjeolgot-sunrise.jpg',
      'https://blog.trazy.com/wp-content/uploads/2019/10/chuam-beach.jpg',
    ],
  ),
  SpotData(
    name: '경포해변',
    description: '강릉의 대표 해변. 경포대에서 바라보는 일출이 유명합니다.',
    lat: 37.8021,
    lng: 128.9088,
    type: SpotType.sunrise,
    tags: ['경포대', '강릉', '해변'],
    shootingTip: '경포대 누각에서 호수와 바다를 함께 담거나, 해변에서 직접 일출을 촬영하세요.',
    compositionTip: '경포대 기둥을 프레임으로 활용하거나, 넓은 백사장을 전경에 두고 원근감을 표현하세요.',
    photoUrls: [
      'https://www.koreatravelpost.com/wp-content/uploads/2020/12/Gyeongpo-sunrise.jpg',
      'https://blog.trazy.com/wp-content/uploads/2019/10/gyeongpo-blog.jpg',
      'https://blog.trazy.com/wp-content/uploads/2022/12/jeongdongjin_sunrise_blog-001.jpg',
    ],
  ),
  SpotData(
    name: '해운대 해변',
    description: '부산의 대표 해변. 동백섬과 함께 보는 일출이 아름답습니다.',
    lat: 35.1587,
    lng: 129.1604,
    type: SpotType.sunrise,
    tags: ['해운대', '부산', '동백섬'],
    shootingTip: '미포 쪽에서 동백섬을 전경에 두고 촬영하거나, 해변 중앙에서 넓은 백사장과 함께 담으세요.',
    compositionTip: '동백섬의 실루엣을 좌측에 배치하고 수평선을 낮게 잡아 하늘의 그라데이션을 강조하세요.',
    photoUrls: [
      'https://blog.trazy.com/wp-content/uploads/2022/12/homigot_sunrise_blog-001.jpg',
      'https://www.koreatravelpost.com/wp-content/uploads/2020/12/Homigot-Sunrise-Festival.jpg',
      'https://blog.trazy.com/wp-content/uploads/2019/10/ulsan-sunset-600x399.jpg',
    ],
  ),
  SpotData(
    name: '광안리 해변',
    description: '광안대교와 함께하는 일출. 야경과 새벽 모두 인기입니다.',
    lat: 35.1532,
    lng: 129.1188,
    type: SpotType.sunrise,
    tags: ['광안대교', '부산', '야경'],
    shootingTip: '해변 중앙에서 광안대교를 배경으로 촬영하면 대교와 일출을 모두 담을 수 있습니다.',
    compositionTip: '대교를 수평으로 가로지르게 배치하고, 해를 우측이나 좌측 교각 근처에 두세요.',
    photoUrls: [
      'https://blog.trazy.com/wp-content/uploads/2023/11/han_river_sunset_blog-001.jpg',
      'https://blog.trazy.com/wp-content/uploads/2019/01/lotte-world-tower.jpg',
      'https://www.koreatravelpost.com/wp-content/uploads/2020/12/Gyeongpo-sunrise.jpg',
    ],
  ),

  // ========== 일몰 명소 ==========
  SpotData(
    name: '을왕리 해변',
    description: '인천공항 인근 서해안 해변. 비행기와 함께하는 일몰로 유명합니다.',
    lat: 37.4454,
    lng: 126.3732,
    type: SpotType.sunset,
    tags: ['비행기', '인천', '해변'],
    shootingTip: '해변 북쪽 끝에서 촬영하면 하늘을 나는 비행기와 석양을 함께 담을 수 있습니다.',
    compositionTip: '비행기 궤적을 대각선으로 활용하고 석양을 배경에 배치해 역동적인 구도를 만드세요.',
    photoUrls: [
      'https://blog.trazy.com/wp-content/uploads/2019/10/daebudo.jpg',
      'https://blog.trazy.com/wp-content/uploads/2023/11/han_river_sunset_blog-001.jpg',
      'https://blog.trazy.com/wp-content/uploads/2019/10/soraepogu-ecological-park.jpg',
    ],
  ),
  SpotData(
    name: '무창포 해변',
    description: '신비의 바닷길이 열리는 곳. 서해안 대표 낙조 명소입니다.',
    lat: 36.2520,
    lng: 126.5385,
    type: SpotType.sunset,
    tags: ['바닷길', '보령', '갯벌'],
    shootingTip: '간조 시간에 열리는 바닷길 위에서 촬영하면 갯벌과 섬, 석양을 모두 담을 수 있습니다.',
    compositionTip: '바닷길을 리딩라인으로 활용하고 원경의 섬을 향해 시선을 유도하세요.',
    photoUrls: [
      'https://blog.trazy.com/wp-content/uploads/2019/10/suncheon-bay.jpg',
      'https://blog.trazy.com/wp-content/uploads/2019/10/daebudo.jpg',
      'https://blog.trazy.com/wp-content/uploads/2023/11/han_river_sunset_blog-001.jpg',
    ],
  ),
  SpotData(
    name: '천수만',
    description: '철새도래지로 유명한 서해안 습지. 넓은 갯벌 위 석양이 장관입니다.',
    lat: 36.5300,
    lng: 126.4400,
    type: SpotType.sunset,
    tags: ['철새', '습지', '서산'],
    shootingTip: '천수만 전망대나 갯벌 산책로에서 철새 떼와 석양을 함께 촬영하세요.',
    compositionTip: '넓은 갯벌을 전경에 두고 철새 실루엣을 중경에 배치해 자연의 광활함을 표현하세요.',
    photoUrls: [
      'https://blog.trazy.com/wp-content/uploads/2019/10/suncheon-bay.jpg',
      'https://blog.trazy.com/wp-content/uploads/2019/10/soraepogu-ecological-park.jpg',
      'https://blog.trazy.com/wp-content/uploads/2019/10/daebudo.jpg',
    ],
  ),
  SpotData(
    name: '선유도',
    description: '군산 앞바다의 아름다운 섬. 명사십리 해변의 일몰이 유명합니다.',
    lat: 35.8255,
    lng: 126.4108,
    type: SpotType.sunset,
    tags: ['섬', '명사십리', '군산'],
    shootingTip: '명사십리 해변의 하얀 모래사장에서 서쪽을 향해 촬영하면 긴 백사장과 석양을 함께 담을 수 있습니다.',
    compositionTip: '파도가 남긴 모래 패턴을 전경에 넣고 수평선을 낮게 잡아 하늘의 색감을 강조하세요.',
    photoUrls: [
      'https://blog.trazy.com/wp-content/uploads/2019/10/daebudo.jpg',
      'https://blog.trazy.com/wp-content/uploads/2019/10/suncheon-bay.jpg',
      'https://blog.trazy.com/wp-content/uploads/2023/11/han_river_sunset_blog-001.jpg',
    ],
  ),
  SpotData(
    name: '마라도',
    description: '대한민국 최남단 섬. 수평선 위로 펼쳐지는 석양이 장관입니다.',
    lat: 33.1142,
    lng: 126.2669,
    type: SpotType.sunset,
    tags: ['최남단', '제주', '등대'],
    shootingTip: '마라도 등대 근처 전망대에서 탁 트인 수평선과 석양을 촬영하세요.',
    compositionTip: '등대나 해안 절벽을 측면에 배치하고 광활한 수평선을 강조한 광각 구도를 사용하세요.',
    photoUrls: [
      'https://triptins.com/wp-content/uploads/2023/03/Udo-Island-View-1024x768.jpeg',
      'https://blog.trazy.com/wp-content/uploads/2019/10/suncheon-bay.jpg',
      'https://triptins.com/wp-content/uploads/2023/03/Seongsan-Ilchulbong-Landscape-1024x768.jpeg',
    ],
  ),
  SpotData(
    name: '협재해변',
    description: '제주 서쪽의 에메랄드 해변. 비양도와 함께하는 일몰이 아름답습니다.',
    lat: 33.3944,
    lng: 126.2397,
    type: SpotType.sunset,
    tags: ['협재', '제주', '비양도'],
    shootingTip: '해변에서 비양도를 중경에 두고 촬영하면 섬과 석양을 함께 담을 수 있습니다.',
    compositionTip: '에메랄드빛 얕은 바다를 전경에 넣고 비양도를 삼분할 좌측에 배치하세요.',
    photoUrls: [
      'https://triptins.com/wp-content/uploads/2023/03/Jeju-Island-Sunrise-Peak-1024x768.jpeg',
      'https://triptins.com/wp-content/uploads/2023/03/Udo-Island-View-1024x768.jpeg',
      'https://www.koreatravelpost.com/wp-content/uploads/2020/12/seongsan-sunrise.jpg',
    ],
  ),
  SpotData(
    name: '태안 꽃지해변',
    description: '할미바위, 할아비바위 사이로 지는 낙조가 유명한 서해안 명소입니다.',
    lat: 36.5012,
    lng: 126.3234,
    type: SpotType.sunset,
    tags: ['꽃지', '태안', '할미바위'],
    shootingTip: '해변에서 두 바위 사이로 해가 지는 순간을 포착하세요. 간조 때 가까이 접근할 수 있습니다.',
    compositionTip: '두 바위를 좌우 대칭으로 배치하고 그 사이 정중앙에 석양을 넣어 균형미를 살리세요.',
    photoUrls: [
      'https://blog.trazy.com/wp-content/uploads/2019/10/daebudo.jpg',
      'https://blog.trazy.com/wp-content/uploads/2019/10/suncheon-bay.jpg',
      'https://blog.trazy.com/wp-content/uploads/2023/11/han_river_sunset_blog-001.jpg',
    ],
  ),
  SpotData(
    name: '제부도',
    description: '바닷길이 열리는 섬. 모세의 기적과 함께하는 일몰이 유명합니다.',
    lat: 37.2412,
    lng: 126.6521,
    type: SpotType.sunset,
    tags: ['바닷길', '화성', '모세의기적'],
    shootingTip: '간조 시간에 열린 바닷길 위에서 육지를 등지고 서해를 향해 촬영하세요.',
    compositionTip: '바닷길을 중앙 리딩라인으로 활용하고 좌우 갯벌과 물웅덩이 반영을 함께 담으세요.',
    photoUrls: [
      'https://blog.trazy.com/wp-content/uploads/2019/10/daebudo.jpg',
      'https://blog.trazy.com/wp-content/uploads/2019/10/soraepogu-ecological-park.jpg',
      'https://blog.trazy.com/wp-content/uploads/2023/11/han_river_sunset_blog-001.jpg',
    ],
  ),
  SpotData(
    name: '변산 채석강',
    description: '천연 절벽과 바다가 만나는 곳. 독특한 지형과 일몰의 조화가 인상적입니다.',
    lat: 35.6298,
    lng: 126.4912,
    type: SpotType.sunset,
    tags: ['채석강', '변산', '절벽'],
    shootingTip: '채석강 절벽 위 전망대에서 층층이 쌓인 퇴적암층과 석양을 함께 촬영하세요.',
    compositionTip: '수평으로 펼쳐진 퇴적암 층을 전경에 넣고 석양을 배경으로 지질학적 특징을 강조하세요.',
    photoUrls: [
      'https://blog.trazy.com/wp-content/uploads/2019/10/suncheon-bay.jpg',
      'https://blog.trazy.com/wp-content/uploads/2019/10/daebudo.jpg',
      'https://blog.trazy.com/wp-content/uploads/2019/10/chuam-beach.jpg',
    ],
  ),

  // ========== 일출+일몰 ==========
  SpotData(
    name: '소매물도',
    description: '통영 앞바다의 작은 섬. 등대섬과 일출·일몰 모두 감상 가능합니다.',
    lat: 34.5833,
    lng: 128.5667,
    type: SpotType.both,
    tags: ['등대섬', '통영', '트레킹'],
    shootingTip: '등대섬으로 이어진 몽돌해변에서 촬영하거나, 망태봉에 올라 섬 전체를 조망하며 찍으세요.',
    compositionTip: '등대섬과 연결된 자갈길을 리딩라인으로 활용하고 등대를 포인트로 배치하세요.',
    photoUrls: [
      'https://blog.trazy.com/wp-content/uploads/2019/10/suncheon-bay.jpg',
      'https://blog.trazy.com/wp-content/uploads/2022/12/homigot_sunrise_blog-001.jpg',
      'https://blog.trazy.com/wp-content/uploads/2019/10/daebudo.jpg',
    ],
  ),
  SpotData(
    name: '다대포 해수욕장',
    description: '부산 서쪽 끝 해변. 낙동강 하구 너머 일몰과 동쪽 일출 모두 볼 수 있습니다.',
    lat: 35.0467,
    lng: 128.9644,
    type: SpotType.both,
    tags: ['분수', '부산', '낙동강'],
    shootingTip: '해변의 음악분수대 근처에서 일몰을 촬영하거나, 몰운대 쪽 언덕에서 전체 해변을 조망하세요.',
    compositionTip: '넓은 백사장과 분수대를 전경에 배치하고 수평선을 낮게 잡아 하늘의 색을 살리세요.',
    photoUrls: [
      'https://blog.trazy.com/wp-content/uploads/2023/11/han_river_sunset_blog-001.jpg',
      'https://blog.trazy.com/wp-content/uploads/2022/12/homigot_sunrise_blog-001.jpg',
      'https://www.koreatravelpost.com/wp-content/uploads/2020/12/Homigot-Sunrise-Festival.jpg',
    ],
  ),
  SpotData(
    name: '안반데기',
    description: '해발 1,100m 고랭지 배추밭. 운해 위 일출과 별빛 석양이 유명합니다.',
    lat: 37.6667,
    lng: 128.7333,
    type: SpotType.both,
    tags: ['운해', '별빛', '강릉'],
    shootingTip: '배추밭이 펼쳐진 언덕 정상에서 360도 파노라마와 운해를 촬영하세요.',
    compositionTip: '고랭지 밭의 이랑을 대각선으로 활용하고 운해를 중경에 두어 깊이감을 표현하세요.',
    photoUrls: [
      'https://blog.trazy.com/wp-content/uploads/2019/01/yangpyeong-paragliding-600x400.jpg',
      'https://blog.trazy.com/wp-content/uploads/2019/10/gyeongpo-blog.jpg',
      'https://www.koreatravelpost.com/wp-content/uploads/2020/12/Gyeongpo-sunrise.jpg',
    ],
  ),
  SpotData(
    name: '우도',
    description: '제주 동쪽의 작은 섬. 검멀레해변 일출과 서빈백사 일몰 모두 인기입니다.',
    lat: 33.5006,
    lng: 126.9512,
    type: SpotType.both,
    tags: ['우도', '제주', '자전거'],
    shootingTip: '일출은 검멀레해변에서, 일몰은 서쪽 서빈백사 해변에서 촬영하세요.',
    compositionTip: '검은 현무암 해안이나 하얀 산호사 해변을 전경에 넣어 제주 섬의 특색을 살리세요.',
    photoUrls: [
      'https://triptins.com/wp-content/uploads/2023/03/Udo-Island-View-1024x768.jpeg',
      'https://triptins.com/wp-content/uploads/2023/03/Jeju-Island-Sunrise-Peak-1024x768.jpeg',
      'https://www.koreatravelpost.com/wp-content/uploads/2020/12/seongsan-sunrise.jpg',
    ],
  ),
  SpotData(
    name: '거제 바람의 언덕',
    description: '드라마 촬영지로 유명한 언덕. 탁 트인 바다와 풍차가 인상적입니다.',
    lat: 34.7412,
    lng: 128.6521,
    type: SpotType.both,
    tags: ['풍차', '거제', '드라마'],
    shootingTip: '언덕 정상의 풍차 근처에서 탁 트인 남해 바다를 배경으로 촬영하세요.',
    compositionTip: '풍차를 측면에 배치하고 언덕의 초원과 바다를 층층이 구성해 원근감을 살리세요.',
    photoUrls: [
      'https://blog.trazy.com/wp-content/uploads/2019/10/suncheon-bay.jpg',
      'https://blog.trazy.com/wp-content/uploads/2019/01/yangpyeong-paragliding-600x400.jpg',
      'https://blog.trazy.com/wp-content/uploads/2019/10/daebudo.jpg',
    ],
  ),
  SpotData(
    name: '여수 향일암',
    description: '남해를 바라보는 사찰. 일출 명소로 유명하며 일몰도 아름답습니다.',
    lat: 34.5912,
    lng: 127.7523,
    type: SpotType.both,
    tags: ['사찰', '여수', '바다'],
    shootingTip: '향일암 법당 앞 전망대에서 기암절벽과 바다, 해를 함께 담으세요.',
    compositionTip: '사찰 처마나 바위를 프레임으로 활용하고 남해 수평선을 배경에 배치하세요.',
    photoUrls: [
      'https://www.koreatravelpost.com/wp-content/uploads/2020/12/Yeosu-Hyangiram-Sunrise.jpg',
      'https://blog.trazy.com/wp-content/uploads/2023/12/naksansa_temple_sunrise_blog-001.jpg',
      'https://blog.trazy.com/wp-content/uploads/2022/12/homigot_sunrise_blog-001.jpg',
    ],
  ),
  SpotData(
    name: '지리산 노고단',
    description: '운해 위로 떠오르는 일출 명소. 대피소에서 1박하며 감상합니다.',
    lat: 35.2912,
    lng: 127.5432,
    type: SpotType.both,
    tags: ['지리산', '운해', '등산'],
    shootingTip: '노고단 정상 대피소 근처에서 운해 위로 떠오르는 해를 촬영하세요.',
    compositionTip: '운해를 전경과 중경에 가득 채우고 산봉우리들을 실루엣으로 레이어링하세요.',
    photoUrls: [
      'https://blog.trazy.com/wp-content/uploads/2019/01/yangpyeong-paragliding-600x400.jpg',
      'https://www.koreatravelpost.com/wp-content/uploads/2020/12/Gyeongpo-sunrise.jpg',
      'https://blog.trazy.com/wp-content/uploads/2019/10/suncheon-bay.jpg',
    ],
  ),
  SpotData(
    name: '대관령 양떼목장',
    description: '넓은 초원과 함께하는 일출. 양떼와 풍력발전기가 어우러진 풍경입니다.',
    lat: 37.6912,
    lng: 128.7321,
    type: SpotType.both,
    tags: ['양떼', '대관령', '목장'],
    shootingTip: '목장 언덕 위에서 풍력발전기와 양떼, 해를 함께 촬영하세요.',
    compositionTip: '양떼를 전경에 배치하고 풍력발전기를 중경에 두어 목가적 풍경을 연출하세요.',
    photoUrls: [
      'https://blog.trazy.com/wp-content/uploads/2019/10/gyeongpo-blog.jpg',
      'https://blog.trazy.com/wp-content/uploads/2019/01/yangpyeong-paragliding-600x400.jpg',
      'https://www.koreatravelpost.com/wp-content/uploads/2020/12/Jeongdongjin-sunrise.jpg',
    ],
  ),
  SpotData(
    name: '영흥도',
    description: '시화방조제로 연결된 섬. 서해 낙조와 동쪽 염전 일출을 함께 즐길 수 있습니다.',
    lat: 37.2500,
    lng: 126.5800,
    type: SpotType.both,
    tags: ['십리포', '인천', '캠핑'],
    shootingTip: '십리포 해변에서 일몰을, 동쪽 염전 지역에서 일출을 촬영하세요.',
    compositionTip: '갯벌과 염전의 물 반사를 활용해 대칭 구도로 하늘과 수면의 색을 강조하세요.',
    photoUrls: [
      'https://blog.trazy.com/wp-content/uploads/2019/10/daebudo.jpg',
      'https://blog.trazy.com/wp-content/uploads/2019/10/soraepogu-ecological-park.jpg',
      'https://blog.trazy.com/wp-content/uploads/2023/11/han_river_sunset_blog-001.jpg',
    ],
  ),
  SpotData(
    name: '비양도',
    description: '제주 한림 앞바다의 작은 화산섬. 사방으로 탁 트인 수평선 조망이 가능합니다.',
    lat: 33.4039,
    lng: 126.2317,
    type: SpotType.both,
    tags: ['화산섬', '한림', '제주'],
    shootingTip: '비양봉 정상에 올라 360도 파노라마로 일출과 일몰을 촬영하세요.',
    compositionTip: '화산섬 특유의 검은 현무암을 전경에 넣고 탁 트인 수평선을 강조하세요.',
    photoUrls: [
      'https://triptins.com/wp-content/uploads/2023/03/Udo-Island-View-1024x768.jpeg',
      'https://triptins.com/wp-content/uploads/2023/03/Seongsan-Ilchulbong-Landscape-1024x768.jpeg',
      'https://www.koreatravelpost.com/wp-content/uploads/2020/12/seongsan-sunrise.jpg',
    ],
  ),
];
